### ISSUE TITLE
Per article / page changefreqs and priorities

### ISSUE THREAD

**Issue by knyghty** [pelican-plugins/sitemap#12]
There are some pages I know I will update more than others, and I might want to nudge the priority up or down, and it's possible that some articles would benefit form this as well. Is it possible to check the metadata for `changefreq` and `priority`?

I'd be happy to contribute this if it's welcome.

**Comment by justinmayer** [comment]
@knyghty: I think that adding support for `changefreq` and `priority` metadata headers to the Sitemap plugin would indeed be a useful feature.

I know it's been a while since you offered to help contribute this enhancement. Please accept my sincere apologies for the delay in responding.

Would you still be interesting in contributing this feature?

**Comment by knyghty** [comment]
It would still be useful to me, I'll try to find some time to look into it 👍

**Comment by justinmayer** [comment]
@dgaylo added this feature via the above-linked PR, which was subsequently released in [Sitemap 1.2.0](https://github.com/pelican-plugins/sitemap/releases/tag/1.2.0) ✨
